[package]
name = "romio"

# When releasing to crates.io:
# - Update html_root_url.
# - Update CHANGELOG.md.
# - Update doc URL.
# - Create "v0.1.x" git tag.
version = "0.1.12"
authors = ["Carl Lerche <me@carllerche.com>", "The Rust Networking Community"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/romio-preview/0.3.0-alpha.9/romio/"
repository = "https://github.com/withoutboats/romio"
description = """
An event-driven, non-blocking I/O platform for writing asynchronous I/O
backed applications, built on top of Rust's standard future API.
"""
categories = ["asynchronous", "network-programming"]
keywords = ["io", "async", "non-blocking", "futures"]

[workspace]

members = [
  "./",
  "romio-async-await",
  "romio-buf",
  "romio-channel",
  "romio-codec",
  "romio-current-thread",
  "romio-executor",
  "romio-fs",
  "romio-io",
  "romio-reactor",
  "romio-signal",
  "romio-threadpool",
  "romio-timer",
  "romio-tcp",
  "romio-tls",
  "romio-udp",
  "romio-uds",
]

[features]
# This feature comes with no promise of stability. Things will
# break with each patch release. Use at your own risk.
async-await-preview = [
  "romio-async-await/async-await-preview",
]

[badges]
travis-ci = { repository = "withoutboats/romio" }
appveyor = { repository = "", id = "" }

[dependencies]
bytes = "0.4"
num_cpus = "1.8.0"
romio-codec = { version = "0.1.0", path = "romio-codec" }
romio-current-thread = { version = "0.1.3", path = "romio-current-thread" }
romio-io = { version = "0.1.6", path = "romio-io" }
romio-executor = { version = "0.1.5", path = "romio-executor" }
romio-reactor = { version = "0.1.1", path = "romio-reactor" }
romio-threadpool = { version = "0.1.4", path = "romio-threadpool" }
romio-tcp = { version = "0.1.0", path = "romio-tcp" }
romio-udp = { version = "0.1.0", path = "romio-udp" }
romio-timer = { version = "0.2.6", path = "romio-timer" }
romio-fs = { version = "0.1.3", path = "romio-fs" }

futures = "0.1.20"

# Needed until `reactor` is removed from `romio`.
mio = "0.6.14"

# Needed for async/await preview support
romio-async-await = { version = "0.1.0", path = "romio-async-await", optional = true }

[target.'cfg(unix)'.dependencies]
romio-uds = { version = "0.2.1", path = "romio-uds" }

[dev-dependencies]
env_logger = { version = "0.5", default-features = false }
flate2 = { version = "1", features = ["romio"] }
futures-cpupool = "0.1"
http = "0.1"
httparse = "1.0"
libc = "0.2"
num_cpus = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"

[patch.crates-io]
romio = { path = "." }
romio-async-await  = { path = "./romio-async-await" }
romio-codec = { path = "./romio-codec" }
romio-current-thread = { path = "./romio-current-thread" }
romio-executor = { path = "./romio-executor" }
romio-fs = { path = "./romio-fs" }
romio-io = { path = "./romio-io" }
romio-reactor = { path = "./romio-reactor" }
romio-signal = { path = "./romio-signal" }
romio-tcp = { path = "./romio-tcp" }
romio-threadpool = { path = "./romio-threadpool" }
romio-timer = { path = "./romio-timer" }
romio-tls = { path = "./romio-tls" }
romio-udp = { path = "./romio-udp" }
romio-uds = { path = "./romio-uds" }
